script:
  - echo "build"
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $AWS_BUCKET
  local_dir: lib
  skip_cleanup: true
  upload-dir: $AWS_UPLOAD_DIR